# Lesson 15

# Regression

You have looked at scatter plots of data in the past (Pandas_Candy_Data*)  
We said that we could use the plots to predict future values. Here we are going to learn how. In middle school you would hear this data fitting technique referred to as "trendlines" in more advanced courses this is generally referred to as "Regression models".  

You will use your understanding of functions such as Linear, Quadratic, Cubic, Exponential, and others to guess what your data (in the scatter plot) looks like.  

We will start with a simple data set.  

<table>
    <thead>
          <th>Distance</th>
          <th>Hang</th>
          <th>R_Strength</th>
          <th>L_Strength</th>	
          <th>R_Flexibility</th>
          <th>L_Flexibility</th>
          <th>O_Strength</th>
    </thead>
    <tbody>
        <tr>
            <td>162.5</td>	    
            <td>4.75</td>	
            <td>170</td>        
            <td>170</td>      
            <td>106</td>	            
            <td>106</td>	           
            <td>240.57</td> 
        </tr>
        <tr>
            <td>144</td>	
            <td>4.07</td>	
            <td>140</td>	
            <td>130</td>	
            <td>92</td>	
            <td>93</td>	
            <td>195.49</td> 
        </tr>
        <tr>
            <td>147.5</td>	
            <td>4.04</td>	
            <td>180</td>	
            <td>170</td>	
            <td>93</td>	
            <td>78</td>	
            <td>152.99</td>  
        </tr>
        <tr>
            <td>163.5</td>
            <td>4.18</td>	
            <td>160</td>	
            <td>160</td>	
            <td>103</td>	
            <td>93</td>	
            <td>197.09</td>  
        </tr>
        <tr>
            <td>192</td>
            <td>4.35</td>	
            <td>170</td>	
            <td>150</td>	
            <td>104</td>	
            <td>93</td>	
            <td>266.56</td>  
        </tr>
        <tr>
            <td>171.75</td>	
            <td>4.16</td>	
            <td>150</td>	
            <td>150</td>	
            <td>101</td>	
            <td>87</td>	
            <td>260.56</td>  
        </tr>
        <tr>
            <td>162</td>
            <td>4.43</td>	
            <td>170</td>	
            <td>180</td>	
            <td>108</td>	
            <td>106</td>	
            <td>219.25</td>  
        </tr>
        <tr>
            <td>104.93</td>	
            <td>3.2</td>	
            <td>110</td>	
            <td>110</td>	
            <td>86</td>	
            <td>92</td>	
            <td>132.68</td>  
        </tr>
        <tr>
            <td>105.67</td>	
            <td>3.02</td>	
            <td>120</td>	
            <td>110</td>	
            <td>90</td>	
            <td>86</td>	
            <td>130.24</td>  
        </tr>
        <tr>
            <td>117.59</td>	
            <td>3.64</td>	
            <td>130</td>
            <td>120</td>
            <td>85</td>	
            <td>80</td>	
            <td>205.88</td>  
        </tr>
        <tr>
            <td>140.25</td>	
            <td>3.68</td>	
            <td>120</td>	
            <td>140</td>	
            <td>89</td>	
            <td>83</td>	
            <td>153.92</td>  
        </tr>
        <tr>
            <td>150.17</td>
            <td>3.6</td>	
            <td>140</td>
            <td>130</td>	
            <td>92</td>	
            <td>94</td>	
            <td>154.64</td>  
        </tr>
        <tr>
            <td>165.17</td>	
            <td>3.85</td>	
            <td>160</td>
            <td>150</td>	
            <td>95</td>	
            <td>95</td>	
            <td>240.57</td>  
        </tr>
    </tbody>
</table>

### Exercise 1 : Load the data into a numpy array

Save the data in an array called `punting_data`

In [ ]:
import numpy as np

#punting_data =